substitutions:
  devicename: main-bedroom
  friendly_name: Main Bedroom
  comment: Main Bedroom Fan and Light Switch

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  comment: ${comment}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $friendly_name Fallback Hotspot
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 115200

tuya:

sensor:
  - platform: wifi_signal
    name: $friendly_name Wifi Signal
    update_interval: 60s

  - platform: uptime
    name: $friendly_name Uptime

light:
  - platform: "tuya"
    name: $friendly_name Light
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: 100
    max_value: 1000
    restore_mode: ALWAYS_OFF

fan:
  - platform: "tuya"
    name: $friendly_name Fan
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    restore_mode: ALWAYS_OFF