esphome:
  name: "upstairs-temp"
  comment: Upstairs Temperature Sensor
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Upstairs Temp Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

sensor:
  - platform: dht
    pin: 32
    model: DHT11
    temperature:
      name: "Upstairs Temperature"
      filters:
       - offset: 0
    humidity:
      name: "Upstairs Humidity"
    update_interval: 30s